version: 0.2


phases:
  install:
  runtime-versions:
    java: corretto11
  commands:
    - echo "Install phase"
pre_build:
  commands:
    - echo "Pre-build phase"
    - mvn clean
build:
  commands:
   - echo "Build phase"
   - mvn package
post_build:
  commands:
    - echo "Post-build phase"
    - mvn verify
artifacts:
  files:
    - target/*.jar